name: REPLACE_TEMPLATE_VARIABLES
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/REPLACE_TEMPLATE_VARIABLES.yml'

jobs:
  replace-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Replace Variables in Files and File Names
        run: |
          find . -type f ! -name 'REPLACE_TEMPLATE_VARIABLES.yml' -exec sed -i 's/{{component_id}}/YOUR_COMPONENT_ID/g' {} \;
          find . -type f ! -name 'REPLACE_TEMPLATE_VARIABLES.yml' -exec sed -i 's/{{component_prefix}}/YOUR_COMPONENT_PREFIX/g' {} \;
          find . -type f ! -name 'REPLACE_TEMPLATE_VARIABLES.yml' -exec sed -i 's/{{component_name}}/YOUR_COMPONENT_NAME/g' {} \;

          # Rename files and directories with variables
          find . -depth -name '*{{component_id}}*' -execdir bash -c 'mv "$1" "${1//{\{\component_id\}\}/YOUR_COMPONENT_ID}"' _ {} \;
          find . -depth -name '*{{component_prefix}}*' -execdir bash -c 'mv "$1" "${1//\{\{component_prefix\}\}/YOUR_COMPONENT_PREFIX}"' _ {} \;
          find . -depth -name '*{{component_name}}*' -execdir bash -c 'mv "$1" "${1//\{\{component_name\}\}/YOUR_COMPONENT_NAME}"' _ {} \;
      - name: Clear and Rebuid Git Index
        run: |
          echo "Clearing Git index"
          rm -f .git/index
          git reset
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replaced template variables"
          git push origin main